In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import matplotlib.patheffects as PathEffects
import matplotlib

In [2]:
import os
import struct
import numpy as np
from utils import *



In [3]:
import sklearn
from sklearn.manifold import TSNE
from time import time

In [4]:
from __future__ import print_function
import argparse
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms
from torch.autograd import Variable

In [5]:
from glow import thops
from glow import modules
from glow import models
from glow.config import JsonConfig
import cv2

glow/utils.py:7: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'module://ipykernel.pylab.backend_inline' by the following code:
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelapp.py", line 486, in start
    self.io_loop.start()
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 1065, in start
    

In [6]:
# negative
path_total = '/home/hyshuai/workspace/dataset/images_background'

dataset_negative = []
for path_p in os.listdir(path_total):
        path_p_join = os.path.join(path_total,path_p)
        for path_c in os.listdir(path_p_join):
            path_real = os.path.join(path_p_join,path_c)
            class_name = path_real
            # image_paths = get_image_paths(path_real)
            images = get_images_frompath(path_real)
            print(class_name," : ",len(images))
            dataset_negative.append(ImageObject(class_name,images))

/home/hyshuai/workspace/dataset/images_background/Grantha/character42  :  20
/home/hyshuai/workspace/dataset/images_background/Grantha/character08  :  20
/home/hyshuai/workspace/dataset/images_background/Grantha/character13  :  20
/home/hyshuai/workspace/dataset/images_background/Grantha/character35  :  20
/home/hyshuai/workspace/dataset/images_background/Grantha/character39  :  20
/home/hyshuai/workspace/dataset/images_background/Grantha/character11  :  20
/home/hyshuai/workspace/dataset/images_background/Grantha/character19  :  20
/home/hyshuai/workspace/dataset/images_background/Grantha/character01  :  20
/home/hyshuai/workspace/dataset/images_background/Grantha/character04  :  20
/home/hyshuai/workspace/dataset/images_background/Grantha/character10  :  20
/home/hyshuai/workspace/dataset/images_background/Grantha/character07  :  20
/home/hyshuai/workspace/dataset/images_background/Grantha/character28  :  20
/home/hyshuai/workspace/dataset/images_background/Grantha/character30  :  20

/home/hyshuai/workspace/dataset/images_background/Tagalog/character02  :  20
/home/hyshuai/workspace/dataset/images_background/Tagalog/character17  :  20
/home/hyshuai/workspace/dataset/images_background/Tagalog/character14  :  20
/home/hyshuai/workspace/dataset/images_background/Tagalog/character09  :  20
/home/hyshuai/workspace/dataset/images_background/Tagalog/character16  :  20
/home/hyshuai/workspace/dataset/images_background/Tagalog/character06  :  20
/home/hyshuai/workspace/dataset/images_background/Hebrew/character08  :  20
/home/hyshuai/workspace/dataset/images_background/Hebrew/character13  :  20
/home/hyshuai/workspace/dataset/images_background/Hebrew/character11  :  20
/home/hyshuai/workspace/dataset/images_background/Hebrew/character19  :  20
/home/hyshuai/workspace/dataset/images_background/Hebrew/character01  :  20
/home/hyshuai/workspace/dataset/images_background/Hebrew/character04  :  20
/home/hyshuai/workspace/dataset/images_background/Hebrew/character10  :  20
/home/

/home/hyshuai/workspace/dataset/images_background/Latin/character11  :  20
/home/hyshuai/workspace/dataset/images_background/Latin/character19  :  20
/home/hyshuai/workspace/dataset/images_background/Latin/character01  :  20
/home/hyshuai/workspace/dataset/images_background/Latin/character04  :  20
/home/hyshuai/workspace/dataset/images_background/Latin/character10  :  20
/home/hyshuai/workspace/dataset/images_background/Latin/character07  :  20
/home/hyshuai/workspace/dataset/images_background/Latin/character15  :  20
/home/hyshuai/workspace/dataset/images_background/Latin/character22  :  20
/home/hyshuai/workspace/dataset/images_background/Latin/character05  :  20
/home/hyshuai/workspace/dataset/images_background/Latin/character03  :  20
/home/hyshuai/workspace/dataset/images_background/Latin/character12  :  20
/home/hyshuai/workspace/dataset/images_background/Latin/character21  :  20
/home/hyshuai/workspace/dataset/images_background/Latin/character02  :  20
/home/hyshuai/workspace/d

/home/hyshuai/workspace/dataset/images_background/Cyrillic/character08  :  20
/home/hyshuai/workspace/dataset/images_background/Cyrillic/character13  :  20
/home/hyshuai/workspace/dataset/images_background/Cyrillic/character11  :  20
/home/hyshuai/workspace/dataset/images_background/Cyrillic/character19  :  20
/home/hyshuai/workspace/dataset/images_background/Cyrillic/character01  :  20
/home/hyshuai/workspace/dataset/images_background/Cyrillic/character04  :  20
/home/hyshuai/workspace/dataset/images_background/Cyrillic/character10  :  20
/home/hyshuai/workspace/dataset/images_background/Cyrillic/character07  :  20
/home/hyshuai/workspace/dataset/images_background/Cyrillic/character28  :  20
/home/hyshuai/workspace/dataset/images_background/Cyrillic/character30  :  20
/home/hyshuai/workspace/dataset/images_background/Cyrillic/character15  :  20
/home/hyshuai/workspace/dataset/images_background/Cyrillic/character22  :  20
/home/hyshuai/workspace/dataset/images_background/Cyrillic/chara

/home/hyshuai/workspace/dataset/images_background/N_Ko/character15  :  20
/home/hyshuai/workspace/dataset/images_background/N_Ko/character22  :  20
/home/hyshuai/workspace/dataset/images_background/N_Ko/character05  :  20
/home/hyshuai/workspace/dataset/images_background/N_Ko/character03  :  20
/home/hyshuai/workspace/dataset/images_background/N_Ko/character27  :  20
/home/hyshuai/workspace/dataset/images_background/N_Ko/character12  :  20
/home/hyshuai/workspace/dataset/images_background/N_Ko/character21  :  20
/home/hyshuai/workspace/dataset/images_background/N_Ko/character32  :  20
/home/hyshuai/workspace/dataset/images_background/N_Ko/character02  :  20
/home/hyshuai/workspace/dataset/images_background/N_Ko/character24  :  20
/home/hyshuai/workspace/dataset/images_background/N_Ko/character17  :  20
/home/hyshuai/workspace/dataset/images_background/N_Ko/character23  :  20
/home/hyshuai/workspace/dataset/images_background/N_Ko/character14  :  20
/home/hyshuai/workspace/dataset/images

/home/hyshuai/workspace/dataset/images_background/Asomtavruli_(Georgian)/character11  :  20
/home/hyshuai/workspace/dataset/images_background/Asomtavruli_(Georgian)/character19  :  20
/home/hyshuai/workspace/dataset/images_background/Asomtavruli_(Georgian)/character01  :  20
/home/hyshuai/workspace/dataset/images_background/Asomtavruli_(Georgian)/character04  :  20
/home/hyshuai/workspace/dataset/images_background/Asomtavruli_(Georgian)/character10  :  20
/home/hyshuai/workspace/dataset/images_background/Asomtavruli_(Georgian)/character07  :  20
/home/hyshuai/workspace/dataset/images_background/Asomtavruli_(Georgian)/character28  :  20
/home/hyshuai/workspace/dataset/images_background/Asomtavruli_(Georgian)/character30  :  20
/home/hyshuai/workspace/dataset/images_background/Asomtavruli_(Georgian)/character15  :  20
/home/hyshuai/workspace/dataset/images_background/Asomtavruli_(Georgian)/character40  :  20
/home/hyshuai/workspace/dataset/images_background/Asomtavruli_(Georgian)/charact

/home/hyshuai/workspace/dataset/images_background/Japanese_(katakana)/character30  :  20
/home/hyshuai/workspace/dataset/images_background/Japanese_(katakana)/character15  :  20
/home/hyshuai/workspace/dataset/images_background/Japanese_(katakana)/character40  :  20
/home/hyshuai/workspace/dataset/images_background/Japanese_(katakana)/character44  :  20
/home/hyshuai/workspace/dataset/images_background/Japanese_(katakana)/character22  :  20
/home/hyshuai/workspace/dataset/images_background/Japanese_(katakana)/character05  :  20
/home/hyshuai/workspace/dataset/images_background/Japanese_(katakana)/character03  :  20
/home/hyshuai/workspace/dataset/images_background/Japanese_(katakana)/character27  :  20
/home/hyshuai/workspace/dataset/images_background/Japanese_(katakana)/character12  :  20
/home/hyshuai/workspace/dataset/images_background/Japanese_(katakana)/character36  :  20
/home/hyshuai/workspace/dataset/images_background/Japanese_(katakana)/character43  :  20
/home/hyshuai/workspa

/home/hyshuai/workspace/dataset/images_background/Sanskrit/character07  :  20
/home/hyshuai/workspace/dataset/images_background/Sanskrit/character28  :  20
/home/hyshuai/workspace/dataset/images_background/Sanskrit/character30  :  20
/home/hyshuai/workspace/dataset/images_background/Sanskrit/character15  :  20
/home/hyshuai/workspace/dataset/images_background/Sanskrit/character40  :  20
/home/hyshuai/workspace/dataset/images_background/Sanskrit/character22  :  20
/home/hyshuai/workspace/dataset/images_background/Sanskrit/character05  :  20
/home/hyshuai/workspace/dataset/images_background/Sanskrit/character03  :  20
/home/hyshuai/workspace/dataset/images_background/Sanskrit/character27  :  20
/home/hyshuai/workspace/dataset/images_background/Sanskrit/character12  :  20
/home/hyshuai/workspace/dataset/images_background/Sanskrit/character36  :  20
/home/hyshuai/workspace/dataset/images_background/Sanskrit/character21  :  20
/home/hyshuai/workspace/dataset/images_background/Sanskrit/chara

/home/hyshuai/workspace/dataset/images_background/Bengali/character22  :  20
/home/hyshuai/workspace/dataset/images_background/Bengali/character05  :  20
/home/hyshuai/workspace/dataset/images_background/Bengali/character03  :  20
/home/hyshuai/workspace/dataset/images_background/Bengali/character27  :  20
/home/hyshuai/workspace/dataset/images_background/Bengali/character12  :  20
/home/hyshuai/workspace/dataset/images_background/Bengali/character36  :  20
/home/hyshuai/workspace/dataset/images_background/Bengali/character43  :  20
/home/hyshuai/workspace/dataset/images_background/Bengali/character21  :  20
/home/hyshuai/workspace/dataset/images_background/Bengali/character32  :  20
/home/hyshuai/workspace/dataset/images_background/Bengali/character02  :  20
/home/hyshuai/workspace/dataset/images_background/Bengali/character24  :  20
/home/hyshuai/workspace/dataset/images_background/Bengali/character17  :  20
/home/hyshuai/workspace/dataset/images_background/Bengali/character23  :  20

In [7]:
# positive

path_positive_total = '/home/hyshuai/workspace/dataset/images_evaluation'
class_name_list = []
for path_p in os.listdir(path_positive_total):
    path_p_join = os.path.join(path_positive_total,path_p)
    for path_c in os.listdir(path_p_join):
        path_real = os.path.join(path_p_join,path_c)
        class_name = path_real
        class_name_list.append(str(class_name))

# class_name = np.array(class_name)
# print(class_name_list)
np.random.seed(66) # 切换类试下
shufindex = np.random.permutation(len(class_name_list))
# print(shufindex)
class_positive = np.array(class_name_list)[shufindex][:20] #取20个类做测试 20-way
print(class_positive)

dataset_train_positive =[]
dataset_test_positive = []
for class_path in class_positive :
    images = get_images_frompath_random(class_path) # 固定随机抽样是否有问题
    print(class_path, " : ", len(images))
    dataset_train_positive.append(ImageObject(class_path, images[:1])) # 5-shot
    dataset_test_positive.append(ImageObject(class_path, images[1:]))



print(len(dataset_train_positive[2].imgs))
print(len(dataset_test_positive[2].imgs))






    

['/home/hyshuai/workspace/dataset/images_evaluation/Glagolitic/character35'
 '/home/hyshuai/workspace/dataset/images_evaluation/Keble/character24'
 '/home/hyshuai/workspace/dataset/images_evaluation/Avesta/character15'
 '/home/hyshuai/workspace/dataset/images_evaluation/Aurek-Besh/character24'
 '/home/hyshuai/workspace/dataset/images_evaluation/Old_Church_Slavonic_(Cyrillic)/character14'
 '/home/hyshuai/workspace/dataset/images_evaluation/Ge_ez/character22'
 '/home/hyshuai/workspace/dataset/images_evaluation/Keble/character21'
 '/home/hyshuai/workspace/dataset/images_evaluation/Mongolian/character14'
 '/home/hyshuai/workspace/dataset/images_evaluation/Oriya/character16'
 '/home/hyshuai/workspace/dataset/images_evaluation/ULOG/character11'
 '/home/hyshuai/workspace/dataset/images_evaluation/Keble/character16'
 '/home/hyshuai/workspace/dataset/images_evaluation/Tengwar/character23'
 '/home/hyshuai/workspace/dataset/images_evaluation/Tibetan/character24'
 '/home/hyshuai/workspace/dataset/

In [8]:
# label:

class_total_num = len(dataset_negative) + len(dataset_train_positive)
print("class_total = ",class_total_num)
np.random.seed(66) 
shufindex = np.random.permutation(class_total_num)
for index, value in enumerate(dataset_negative):
    value.label = shufindex[index]
    print(value.name,  value.label)

for index, value in enumerate(dataset_train_positive):
    value.label = shufindex[index+len(dataset_negative)]
    dataset_test_positive[index].label = shufindex[index+len(dataset_negative)]
    print(value.name, value.label)

class_total =  984
/home/hyshuai/workspace/dataset/images_background/Grantha/character42 847
/home/hyshuai/workspace/dataset/images_background/Grantha/character08 118
/home/hyshuai/workspace/dataset/images_background/Grantha/character13 364
/home/hyshuai/workspace/dataset/images_background/Grantha/character35 239
/home/hyshuai/workspace/dataset/images_background/Grantha/character39 76
/home/hyshuai/workspace/dataset/images_background/Grantha/character11 936
/home/hyshuai/workspace/dataset/images_background/Grantha/character19 621
/home/hyshuai/workspace/dataset/images_background/Grantha/character01 275
/home/hyshuai/workspace/dataset/images_background/Grantha/character04 121
/home/hyshuai/workspace/dataset/images_background/Grantha/character10 312
/home/hyshuai/workspace/dataset/images_background/Grantha/character07 380
/home/hyshuai/workspace/dataset/images_background/Grantha/character28 298
/home/hyshuai/workspace/dataset/images_background/Grantha/character30 727
/home/hyshuai/worksp

In [9]:
# test_class_index = [159, 687, 486, 843, 27, 253, 909, 295, 912, 714, 307, 661, 858, 79, 717, 122, 51, 631, 828, 20]
test_class_index = [data.label for data in dataset_train_positive]
print(test_class_index)

[159, 687, 486, 843, 27, 253, 909, 295, 912, 714, 307, 661, 858, 79, 717, 122, 51, 631, 828, 20]


In [10]:
# print(dataset_test_positive[0].name)
# np.random.shuffle(dataset_test_positive)
# print(dataset_test_positive[0].name)
# imgs_show(np.squeeze( dataset_test_positive[0].imgs),1,5) 
# imgs_show(np.squeeze(dataset_negative[1].imgs),4,5)


In [11]:
# print(dataset_negative[0].imgs[2].shape)
# # print(im[15])
# # print(im.shape)
# print(dataset_negative[0].imgs[0].shape)
x = [data.imgs for data in dataset_train_positive] 
print(x[0][0].shape)
img_show(np.squeeze(x[0]))
img_show(np.squeeze(x[1]))
img_show(np.squeeze(x[2]))
img_show(np.squeeze(x[3]))
img_show(np.squeeze(x[4]))

(1, 32, 32)


NameError: name 'img_show' is not defined

In [12]:

def get_next_perfect(dataset_train_positive,dataset_negative,p_size,n_size):
    """
    final batch_size = p_size + n_size * 2
    every dataset_negative should have same imgs leng
    """
    #shuffle
    np.random.shuffle(dataset_train_positive)
    np.random.shuffle(dataset_negative)
    for data in dataset_negative:
        np.random.shuffle(data.imgs)
    for data in dataset_train_positive:
        np.random.shuffle(data.imgs)
    
    
    batch_negative = n_size * 2
#     print('batch_negative ',batch_negative)
    len_n_class = len(dataset_negative)
#     print('len_n_class ',len_n_class)
    len_p_class = len(dataset_train_positive)
#     print('len_p_class ',len_p_class)
    len_n_imgs = len(dataset_negative[0].imgs)
#     print('len_n_imgs ',len_n_imgs)
    len_p_imgs = len(dataset_train_positive[0].imgs)
    
    negative_number = 0
    
    
#     shuffindex = np.random.permutation(len_n)
# #     print(shuffindex)
#     np.random.shuffle(dataset_train_positive)
#     np.random.shuffle(dataset_negative)
    
    for data in dataset_negative:
        negative_number += len(data.imgs)
#         np.random.shuffle(data.imgs)
#     print('negative_number ',negative_number)
    batch_total = negative_number  // batch_negative
#     print('batch_total ',batch_total)
    i_n_class = 0
    i_n_img = 0
    i_p_class = 0
    i_p_img = 0
    
    
    
        
    
    for b in range(batch_total):
        train_x =[]
        train_y = []
        create_negative_imgs = 0
        while create_negative_imgs <= (batch_total * batch_negative) and create_negative_imgs < batch_negative:
            
            # while #如果一次循环没够，需要再次循环
            if i_n_class >= len_n_class:
                    i_n_class = 0
                    i_n_img +=1
                    if (i_n_img+1) *2 >len_n_imgs:
                        i_n_img = 0
#                     print('if i_n_class >= len_n_class i_n_class ',i_n_class)
#                     print('if i_n_class >= len_n_class i_n_img ',i_n_img)
            
            for i in range(i_n_class,len_n_class):
                    
#                 print('for i in range(i_n_class i_n_class ',i_n_class)
#                 print('for i in range(i_n_class i_n_img ',i_n_img)
                train_x += dataset_negative[i_n_class].imgs[i_n_img * 2 : (i_n_img+1) *2]
                train_y += [dataset_negative[i_n_class].label] * 2
                
                i_n_class+=1
                if i_n_class >= len_n_class:
                    i_n_class = 0
                    i_n_img +=1
                    if (i_n_img+1) *2 > len_n_imgs:
                        i_n_img = 0
#                     print('if i_n_class >= len_n_class i_n_class ',i_n_class)
#                     print('if i_n_class >= len_n_class i_n_img ',i_n_img)
            
                create_negative_imgs +=2
                if create_negative_imgs >= batch_negative:
#                     print("create_negative_imgs ok ",create_negative_imgs)
                    break
                    
                
        create_positive_imgs = 0    
        while create_positive_imgs < p_size:
            for i in range(i_p_class,len_p_class):
#                 print('for i in range(i_p_class     ',i_p_class)
#                 print('for i in range(i_p_img  ',i_p_img)
                
                train_x += dataset_train_positive[i_p_class].imgs[i_p_img:(i_p_img +1)]
                train_y += [dataset_train_positive[i_p_class].label]
                
                i_p_class+=1
                if i_p_class >= len_p_class:
                    i_p_class = 0
                    i_p_img +=1
                    if (i_p_img +1) > len_p_imgs:
                        i_p_img = 0
#                     print('if i_p_class >= len_p_class i_p_class ',i_p_class)
#                     print('if i_p_class >= len_p_class i_p_img ',i_p_img)
                
                create_positive_imgs+=1
                if create_positive_imgs >= p_size:
#                     print("create_positive_imgs ok ",create_positive_imgs)
                    break
        
        shuffindex_out = np.random.permutation(len(train_y))
#         print(train_x[0].shape)
        train_x = np.stack(train_x,axis = 0)
#         print('after concat : ',train_x[0].shape)
        train_x = train_x[shuffindex_out]
        train_y = np.array(train_y)[shuffindex_out]
        
        yield train_x,train_y  

In [13]:
dataaaaaaa = get_next_perfect(dataset_train_positive,dataset_negative,8,126)
for x ,y in dataaaaaaa:
    print(y)
    print('x o shape ' ,x.shape,y.shape)
    print("one batch is over")


[ 43 920 239 697 112 506 940 301 794 558  80 602 486 916 363 911 505  43
 795 236  52 921 827 841 219 950 598 406 645 795 911 956 226 485 591 524
 614 197 117 484 714 421 747 641 928 646 349 864 117 632 419  20 457 790
 100 260 389 632 668  36 195 543 356 569 339 628 514  89 796 412 675  39
 506 401 454 195 295 756 107 864 677 396 455 731  51  52 396 363 253 181
 127 543 394 533  92 660  29 527 677 454 916 631 182  15 959 527  54 818
 455 112 476 182 249 383 707 569 955 558 107 236  39  87 242 301 293 517
  59 716 600 316  89 287 524 133 541 591 940 235  36 717 484 959 349 517
 734 646 446 955 917 181 707 419 641 712 648 457 827  49 928 921 533 235
 383  64 923 660 796 219 648  92 790 446 135  59 209 167 628 678 905 133
 389  49 197  29 697 336 945  64  54 734 485  85 476  80 245 421 239 209
 775 541 602 514 678 917 747 316 339 775 890 756 961 712 920  87 890 402
 249 356 728 127 406  85 923 818 600 896 401 242 245 167 668 135 675 731
 505  15 412 614 645 287 896 226 402 961 841 950 95

x o shape  (260, 1, 32, 32) (260,)
one batch is over
[ 85  36 412 383 756 133 980 356 668 514 187 955 728 796 394 959 920 955
 734 301 928 485  43 604 716 293 614 645 527 859 517 209 506  92 945 940
 779 980 945 747 914 209 419 533 485 794 920 598 419 600 472 697 604 916
 731 827 112 349 591 242 916 600 890 181 396 527 591 349 506 135 219  36
 316  54 197  87 950 912 921 236 371 383 707 406 796 226 961 245 394 905
 558 668 375 524 677 159  24 917 905 371 396  64 660 117 446 675 472 149
 775 716 239 790 641 412 287 921 675  87 133 421 167 479 660  92 479 195
 641 914  24 602 454 293 455 406 959 795  52 505 245 356 728 107  27 677
 226 775 127  29  85 339 569 182 628 911 632 558  43 514  49 956 100 219
 896 950 896 928 135 661 336 901 541 122  54 543 569 107 795 923 648 454
  79 827 339  49 909 127 446  80 632 239 790 197 181 645 841 731 712 901
  64 149  59 517 956 687 476 864 712 301 917 112  80 182 911 614 890 260
 363 421 100 779 747 859 117 476 236 697 628 541 818 841 195 794 260 24

In [14]:
def getnext_test(dataset_test_positive,test_class_index):
    
    for data in dataset_test_positive:
        x = np.stack(data.imgs,axis =0)
        y = np.array([test_class_index.index(data.label)] * len(data.imgs))
        yield x,y

In [15]:
dataaaaaaa = getnext_test(dataset_test_positive,test_class_index)
for x ,y in dataaaaaaa:
    print(y)
    print(x.shape,y.shape)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
(19, 1, 32, 32) (19,)
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
(19, 1, 32, 32) (19,)
[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
(19, 1, 32, 32) (19,)
[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
(19, 1, 32, 32) (19,)
[4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4]
(19, 1, 32, 32) (19,)
[5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
(19, 1, 32, 32) (19,)
[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
(19, 1, 32, 32) (19,)
[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
(19, 1, 32, 32) (19,)
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
(19, 1, 32, 32) (19,)
[9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9]
(19, 1, 32, 32) (19,)
[10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10]
(19, 1, 32, 32) (19,)
[11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11]
(19, 1, 32, 32) (19,)
[12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12]
(19, 1, 32, 32) (19,)
[13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13]
(19, 1, 32, 32) (19,)
[14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 1

In [16]:
def imgs_show_norm(imgs,row,col):
    fig,ax = plt.subplots(nrows=row,ncols=col,sharex=True,sharey=True)
    ax = ax.flatten()
    for i in range(row*col):
        img = imgs[i]
        min = np.min(img)
#         print('min = ',min)
        img = np.subtract(img,min) # 0->
        max = np.max(img)
#         print('max =',max)
        img = np.divide(img,max)
        
        ax[i].imshow(img,cmap='Greys', interpolation='nearest')
    
    ax[0].set_xticks([])
    ax[0].set_yticks([])
    plt.tight_layout()
    plt.show()

In [17]:
def img_show_norm(img):
    min_ = np.min(img)
#     print('min = ',min_)
    img = np.subtract(img,min_) # 0->
    max_ = np.amax(a = img,keepdims=False)
#     print('max =',max_)
    img = np.divide(img,max_)  # 0->1
#     print(img)
    plt.figure(figsize=(1,1))
    plt.imshow(img,cmap='Greys',interpolation='nearest')

In [18]:
def img_show(img):
    plt.figure(figsize=(1,1))
    plt.imshow(img,cmap='Greys',interpolation='nearest')
    

In [19]:
def imgs_show(imgs,row,col):
    fig,ax = plt.subplots(nrows=row,ncols=col,sharex=True,sharey=True)
    ax = ax.flatten()
    for i in range(row*col):
        img = imgs[i]
        
        ax[i].imshow(img,cmap='Greys', interpolation='nearest')
    
    ax[0].set_xticks([])
    ax[0].set_yticks([])
    plt.tight_layout()
    plt.show()
    
    

In [20]:
def compute_index_logical_equal(inputs,indexs):
    logic_result = (inputs==indexs[0])
    for value in indexs:
        logic_result = np.logical_or(inputs == value,logic_result)
    return logic_result


In [23]:
# nb_digits = class_total_num
net_auto = models.Glow(JsonConfig("hparams/omni_all_bg.json"),test_class_index,is_mean=False,K=8,y_classes=class_total_num,is_split_2d=False)


In [24]:
# for param in net_auto.parameters():
#     print(param.data.size())
# net_auto.load_state_dict(torch.load('model_glow_ominst_all_bg_8k_20_way_778.pt'))
    

In [25]:

# net_auto = torch.load('model_autoEncode5.pkl')
# net_auto.load_state_dict(torch.load('model_glow_ominst19000.pt'))
# net_auto.load_state_dict(torch.load('model_glow_ominst_no_split2d_4k_4316.pt'))
# net_auto.load_state_dict(torch.load('model_glow_ominst_no_split2d_8k_9000.pt'))
use_cuda = torch.cuda.is_available()
torch.manual_seed(666)
device = torch.device("cuda" if use_cuda else "cpu")
net_auto.to(device)
net_auto.float()


criterion = nn.MSELoss()
optimizer = optim.Adam(net_auto.parameters(),lr=0.001,weight_decay=1e-5) # decoder don't weight_decay


In [28]:
#X_train_nor
batch_size = 256
net_auto.train()
for epoch in range(30001):
    #train:
    
    datas =  get_next_perfect(dataset_train_positive,dataset_negative,8,124)
#     datas = getnext(dataset_train_positive,dataset_negative)
    
    trainloss_g = 0
    trainloss_c = 0
    
    for x,y in datas:
        inputs ,lables = torch.from_numpy(x).float().to(device),\
            torch.from_numpy(y).long().to(device)
#         print(torch.sum(lables)) # = 1167
        
        y_onehot = torch.FloatTensor(batch_size, class_total_num).to(device)
        y_onehot.zero_()
        y_onehot.scatter_(1, lables.view(-1,1), 1)
#         print('y_onehot:', y_onehot)


       

        optimizer.zero_grad()
#         z, det, y_logits = net_auto(x=inputs, y_onehot=y_onehot)
        
        z, det = net_auto(x=inputs, y_onehot=y_onehot)
        y_logits = net_auto.class_flow(z)
        
#         print(z.size())
#         print(det)
        loss_g = models.Glow.loss_generative(det)
        loss_c = models.Glow.loss_class(y_logits,lables)
        print('loss_g = ',loss_g.item())
        print('loss_c =  ',loss_c.item())
        loss = loss_g + loss_c * 0.1
        loss.backward()
        torch.nn.utils.clip_grad_value_(net_auto.parameters(), 5)
        torch.nn.utils.clip_grad_norm_(net_auto.parameters(), 100)
        
        
        trainloss_g += loss_g.item()
        trainloss_c += loss_c.item()
#         print("net_auto.conv_d1 grad:",net_auto.conv_d1.weight.grad)
        
#         print("after net_auto.conv_1 grad:",net_auto.conv1.weight.grad)
        optimizer.step()
        
    print('%d  gloss: %.3f, class loss:%.3f' % (epoch ,  trainloss_g,trainloss_c))
    
    if epoch % 100 == 0 and epoch >0:
        torch.save(net_auto.state_dict(),'model_glow_ominst_all_bg_8k_20_way_no_split_no_mean_'+str(epoch)+'.pt')
    


loss_g =  2.62449288368
loss_c =   0.118488185108
loss_g =  2.66281509399
loss_c =   0.161902546883
loss_g =  2.64986157417
loss_c =   0.124992713332
loss_g =  2.68118476868
loss_c =   0.198284432292
loss_g =  2.65887069702
loss_c =   0.215503707528
loss_g =  2.67272496223
loss_c =   0.0941700041294
loss_g =  2.60549092293
loss_c =   0.160873487592
loss_g =  2.6691262722
loss_c =   0.117325894535
loss_g =  2.67118930817
loss_c =   0.0696813240647
loss_g =  2.65003347397
loss_c =   0.112067833543
loss_g =  2.66517233849
loss_c =   0.161297261715
loss_g =  2.65900707245
loss_c =   0.173803955317
loss_g =  2.66064333916
loss_c =   0.0951187238097
loss_g =  2.66123914719
loss_c =   0.101577743888
loss_g =  2.63018751144
loss_c =   0.244709864259
loss_g =  2.68177318573
loss_c =   0.0753934979439
loss_g =  2.61173534393
loss_c =   0.0630199536681
loss_g =  2.64725351334
loss_c =   0.226816922426
loss_g =  2.66817998886
loss_c =   0.0683513954282
loss_g =  2.66117358208
loss_c =   0.09727784

KeyboardInterrupt: 

In [27]:
net_auto.train()
torch.save(net_auto.state_dict(),'model_glow_ominst_all_bg_8k_20_way_no_split_no_mean_1092.pt')

In [ ]:
use_cuda = torch.cuda.is_available()
torch.manual_seed(666)
device = torch.device("cuda" if use_cuda else "cpu")
net_auto.to(device)
net_auto.float()
net_auto.eval()

test_loss = 0
correct = 0
test_datas = getnext_test(dataset_test_positive,test_class_index)
for x ,y in test_datas:
        inputs, labels = Variable(torch.from_numpy(x).float()).cuda(), Variable(torch.from_numpy(y).long()).cuda()
        print(labels)
        
        z, det = net_auto(x=inputs, y_onehot=None)
        classify = net_auto.class_flow(z)
        
        
        
#         _,classify = net_auto(inputs)
        test_loss += F.nll_loss(classify, labels, size_average=False).item() # sum up batch loss
#         print(classify)
        pred = classify.max(1,keepdim=True)[1]
#         print(pred)
        
        correct += pred.eq(labels.view_as(pred)).sum().item()
#         print(correct)
print(correct)
print(correct * 1.0 / (19 * 20))
print(test_loss)

In [ ]:
criterion = nn.MSELoss(reduction='sum')
ones_tensor = torch.ones((1, 32, 32)).float().cuda()

from scipy import misc
import time

In [ ]:
# net_auto.load_state_dict(torch.load('model_glow_ominst2000.pt'))


# use_cuda = torch.cuda.is_available()
# torch.manual_seed(666)
# device = torch.device("cuda" if use_cuda else "cpu")
# net_auto.to(device)
# net_auto.float()
# net_auto.load_state_dict(torch.load('model_glow_ominst_no_split2d_no_z_mean_no_add_normal1223.pt'))

# net_auto.load_state_dict(torch.load('model_glow_ominst_no_split2d_8k_9000.pt'))
# net_auto.train()
# torch.save(net_auto.state_dict(),'model_glow_ominst_all_bg_8k_20_way_778.pt')

def sample_and_save(sample_p,p,sampe_index_num):
    
    sample_n = np.random.randint(964)
#     sample_index = np.random.randint(18)
    sample_index = np.random.permutation(20)[:2]
    
    print('sample_p = {},sample_n ={}, sample_index = {}'.format(sample_p,sample_n,sample_index))

    posi = np.concatenate(( np.array(dataset_train_positive[sample_p].imgs)  ,  np.array(dataset_negative[sample_n].imgs)[sample_index]   ))
    labl =  np.array([dataset_train_positive[sample_p].label, dataset_negative[sample_n].label,dataset_negative[sample_n].label])
    print(dataset_train_positive[sample_p].name)
    save_path = dataset_train_positive[sample_p].name.split('/home/hyshuai/workspace/dataset/images_evaluation/')[1]
    save_path = './generate_img/' + str(save_path)
    
    if not os.path.isdir(save_path):
        os.makedirs(save_path)
    print(save_path)
    
    inputs ,lables = torch.from_numpy(posi).float().to(device),\
                torch.from_numpy(labl).long().to(device)

    y_onehot = torch.FloatTensor(3, class_total_num).to(device)
    y_onehot.zero_()
    y_onehot.scatter_(1, lables.view(-1,1), 1)
    # print('y_onehot:', y_onehot)
    # z, det, y_logits = net_auto(x=inputs, y_onehot=y_onehot)
    z, det = net_auto(x=inputs, y_onehot=y_onehot)
    y_logits = net_auto.class_flow(z)
    
    
    obj = z[0] 
    nn_index = [-1,1]
#     print(torch.sum(torch.abs(z[2]),dim =(1,2)))
#     print(torch.sum(torch.abs(z[1]),dim =(1,2)))

#     print(torch.sum(torch.abs(z[0]),dim =(1,2)))
    #         p = np.random.normal(loc=0.5,scale=0.1)
    q = np.random.randint(0, 2)
    scale = nn_index[q] * p
    # print('scale = ', scale)
#     start_index = np.random.randint(0,44)
    # start_index = 0
#     end_index = start_index + 20

    slic_index = np.random.permutation(64)[:sampe_index_num]
#     print(slic_index) 

#     print('scale = {},start_index ={}, end_index = {}'.format(scale,start_index,end_index))
    # obj[start_index:end_index] = obj[start_index:end_index] + scale * (z[1][start_index:end_index] - z[2][start_index:end_index])
    obj[slic_index] = obj[slic_index] + scale * (z[1][slic_index] - z[2][slic_index])

    # print(obj.size())
    obj = obj.view(-1,*obj.size())
    # print(obj.size())
    obj_oneshot = y_onehot[0].view(-1,class_total_num)
    
    
    
    x_ = net_auto(z = obj,y_onehot = obj_oneshot,eps_std = None ,reverse=True)

    x_ = torch.clamp(x_,-1,1)
    
    diffrent_b = criterion(x_[0] , inputs[0]) / criterion(inputs[0],ones_tensor)
    print(' diffrent_b = ',diffrent_b)

    c_self = criterion(inputs[0],ones_tensor)
    
    x_ = np.squeeze(x_.data.cpu().numpy())
#     print(x_.shape)
    tt = int(round(time.time() * 1000))
    misc.imsave(save_path+"/"+str(tt)+"_"+str(diffrent_b.data.cpu())+ ".png",x_)
#     x_ = cv2.imwrite()
    

    



In [ ]:
for i in range(14,20):

    for _ in range(10000):

        sample_and_save(i,0.5,64)

In [ ]:
sample_p = 0 # np.random.randint(20)  # 10 # 
sample_n = np.random.randint(964)
sample_index = np.random.randint(18)
print('sample_p = {},sample_n ={}, sample_index = {}'.format(sample_p,sample_n,sample_index))

posi = np.concatenate(( np.array(dataset_train_positive[sample_p].imgs)  ,  np.array(dataset_negative[sample_n].imgs[sample_index:sample_index+2])   ))
labl =  np.array([dataset_train_positive[sample_p].label, dataset_negative[sample_n].label,dataset_negative[sample_n].label])
print(dataset_train_positive[sample_p].name)
inputs ,lables = torch.from_numpy(posi).float().to(device),\
            torch.from_numpy(labl).long().to(device)
        
y_onehot = torch.FloatTensor(3, class_total_num).to(device)
y_onehot.zero_()
y_onehot.scatter_(1, lables.view(-1,1), 1)
# print('y_onehot:', y_onehot)
# z, det, y_logits = net_auto(x=inputs, y_onehot=y_onehot)
z, det = net_auto(x=inputs, y_onehot=y_onehot)
y_logits = net_auto.class_flow(z)


print('z.size() ' ,z.size())
print('y_logits.size() ' ,y_logits.size())
print(y_logits[1][1])

In [ ]:
obj = z[0]
# print(obj[0])
obj = z[0] 
nn_index = [-1,1]
print(torch.sum(torch.abs(z[2]),dim =(1,2)))
print(torch.sum(torch.abs(z[1]),dim =(1,2)))

print(torch.sum(torch.abs(z[0]),dim =(1,2)))
p =  1.0 # np.random.uniform(0.5, 0.8)
#         p = np.random.normal(loc=0.5,scale=0.1)
q = np.random.randint(0, 2)
scale = nn_index[q] * p
# print('scale = ', scale)
start_index = np.random.randint(0,44)
# start_index = 0
end_index = start_index + 20

slic_index = np.random.permutation(64)[:20]
print(slic_index) 

print('scale = {},start_index ={}, end_index = {}'.format(scale,start_index,end_index))
# obj[start_index:end_index] = obj[start_index:end_index] + scale * (z[1][start_index:end_index] - z[2][start_index:end_index])
obj[slic_index] = obj[slic_index] + scale * (z[1][slic_index] - z[2][slic_index])

# print(obj.size())
obj = obj.view(-1,*obj.size())
# print(obj.size())
obj_oneshot = y_onehot[0].view(-1,class_total_num)
# print(obj_oneshot.size())
# print(obj_oneshot)
# print(obj[0][0])

In [ ]:
# z = z.detach().cpu().numpy()
# print(z.size())
# print(z[0][0][0])
x_ = net_auto(z = obj,y_onehot = obj_oneshot,eps_std = None ,reverse=True)

x_ = torch.clamp(x_,-1,1)
print(x_.size())

print("abs sum = ",torch.sum(torch.abs(x_[0] - inputs[0])))
# print("abs sum = ",torch.sum(x_[0]- inputs[0]))
c = criterion(x_[0] , inputs[0])
print("criterion sum   = ",c)

c_self = criterion(inputs[0],ones_tensor)
print("self criterion sum  = ",c_self)
dd =  torch.sum(torch.mul(x_[0],inputs[0]))
print("  sum  = ",  dd )
m1 = torch.norm(x_[0])
print("  sum  = ",  m1 )
m2 = torch.norm(inputs[0])
print("  sum  = ",  m2 )

# l2_self = torch.sum(np.square(x_[0] - inputs[0]))
# print("l2_self sum  = ",l2_self)

print("l2  bi li   = ",c / c_self)
print("cos distance   = ",dd  / (m1 * m2) )

In [ ]:
img_show(np.squeeze(x_.data))
img_show(np.squeeze(inputs.data[0]))
imgs_show(np.squeeze(inputs.data),1,3)

In [ ]:
train_img_list = [data.imgs for data in dataset_train_positive]
train_name_list = [data.name for data in dataset_train_positive]
imgs_show(np.squeeze(np.array(train_img_list)),4,5)
print(train_name_list)

In [ ]:
def img_show(img):
    plt.figure(figsize=(1,1))
    plt.imshow(img,cmap='Greys',interpolation='nearest')

In [ ]:
# import seaborn as sns
# sns.set_style('darkgrid')
# sns.set_palette('muted')
# sns.set_context("notebook", font_scale=1.5,
# rc={"lines.linewidth": 2.5})

label_class = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
tsne = TSNE(n_components=2, init='pca', random_state=501)
X = np.squeeze(np.array(train_img_list))

X = np.reshape(X,(-1,32 * 32))
print(X.shape)
result = tsne.fit_transform(X)

t0 = time()

fig = plot_embedding(result, test_class_index,'t-SNE embedding of the digits (time %.2fs)'% (time() - t0))
plt.show(fig)

In [ ]:
# plt.axis([0, 1000, 0, 1])
# plt.ion()
 
# while True:
#     x = []
#     y = []
#     for i in range(512):
#         x.append(i)
#         y.append(np.random.random())
#         # plt.pause(0.05)
#     plt.cla()
#     plt.plot(x, y)
#     plt.pause(0.033)


In [ ]:
dataaaaaaa = get_next_perfect(dataset_train_positive,dataset_negative,8,126)

z_list = []
labels_list = []
for x ,y in dataaaaaaa:
    inputs, labels = Variable(torch.from_numpy(x).float()).cuda(), Variable(torch.from_numpy(y).long()).cuda()
    print(labels)
    z, det = net_auto(x=inputs, y_onehot=None)
    z_list.append(z.data.cpu())
    labels_list.append(y)
print(len(z_list))
print(len(labels_list))
    


In [ ]:
z_array = np.concatenate(z_list)
print(z_array.shape)
labels_array = np.concatenate(labels_list)
print(labels_array.shape)

In [ ]:
z_review = np.reshape(z_array,(-1,64 * 4 * 4))
print(z_review.shape)

In [ ]:
def plot_embedding(data, label, title):
    x_min, x_max = np.min(data, 0), np.max(data, 0)
    data = (data - x_min) / (x_max - x_min)

    fig = plt.figure(figsize=(50,50))
    ax = plt.subplot(111)
    for i in range(data.shape[0]):
        plt.text(data[i, 0], data[i, 1], str(label[i]),
                 color=plt.cm.Set1(label[i] / 989.),
                 fontdict={'weight': 'bold', 'size': 9})
    plt.xticks([])
    plt.yticks([])
    plt.title(title)
    return fig

In [ ]:
tsne = TSNE(n_components=2, init='pca', random_state=666)

result_z = tsne.fit_transform(z_review[:2000])

t0 = time()



In [ ]:
# print()
fig = plot_embedding(result_z, labels_array[:2000],'t-SNE embedding of the digits (time %.2fs)'% (time() - t0))
plt.show(fig)